= {product} FAQs
:navtitle: FAQs

If you are new to {product} and its {pulsar} enhancements, these FAQs are for you.

== What is {product}?

{product} is a Kubernetes-based distribution of {pulsar}, based on the technology that https://kesque.com/[Kesque] built to run its {pulsar-short}-as-a-service.

== Are {product} and {company} Luna Streaming the same offering?

Yes.
include::partial$luna-name.adoc[]

== What components and features are provided by {product}?

In addition to {pulsar} itself, {product} provides:

* An installer that can stand up a dev or production cluster on bare metal or VMs without a pre-existing Kubernetes environment
* A Helm chart that can deploy and manage {pulsar-short} on your current Kubernetes infrastructure
* {cass-short}, Elastic, Kinesis, {kafka-reg}, and JDBC connectors
* A management dashboard
* A monitoring and alerting system

== On which version of {pulsar} is {product} based?

{product} {luna-version} is based on its distribution of {pulsar} {pulsar-version}, plus features and additional enhancements from {company} contributors.

== What does {product} provide that I cannot get with open-source {pulsar}?

{product} is a hardened version of {pulsar} that been run through additional testing to ensure it is ready for production use. It also includes additional tooling to help monitor your system, including an enhanced Admin Console and a Heartbeat service to monitor the system health.

== Is {product} an open-source project?

Yes, {product} is open source. See the <<gitHubRepos,repos FAQ>>.

== Which Kubernetes platforms are supported by {product}?

They include Minikube, K8d, Kind, Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service (AKS), Amazon Elastic Kubernetes Service (EKS), and other commonly used platforms.

[#gitHubRepos]
== Where are the {product} public GitHub repos?

There are several public repos, each with a different purpose. See:

* {pulsar-repo}[{pulsar-repo}]: This is the distro repo (a fork of `apache/pulsar`).
* {pulsar-admin-console-repo}[{pulsar-admin-console-repo}]: This is the repo for the {pulsar-short} admin console, which allows for the configuration and monitoring of {pulsar-short}.
* {pulsar-heartbeat-repo}[{pulsar-heartbeat-repo}] : This is a monitoring/observability tool for {pulsar-short} that tracks the health of the cluster and can generate alerts in Slack and OpsGenie.
* {kaap-operator-repo}[{kaap-operator-repo}]: Use the {kaap-short} to deploy the {company} {pulsar-short} Distro in an existing Kubernetes cluster.
+
{company} recommends the {kaap-short} as a replacement for the deprecated {pulsar-helm-chart-repo}[{company} {pulsar-short} Helm chart].
* {pulsar-sink-repo}[{pulsar-sink-repo}]: This is the {company} {pulsar} Connector (`pulsar-sink`) repo.

== Is there a prerequisite version of Java needed for the {product} installation?

The {product} distribution is designed for Java 17. However, because the product releases Docker images, you do not need to install Java 17 in advance. Java 17 is bundled in the Docker image.

== What are the install options for {product}?

* **{kaap-short} Helm chart (Recommended)**: Use the {company} {kaap-operator-repo}[{kaap-short} Helm chart], which provides Kubernetes-native autoscaling and simplified management for {pulsar} clusters. For more information, see the xref:kaap-operator::index.adoc[{kaap}] documentation.
* **{product} Helm chart (Deprecated)**: The Helm chart provided at {pulsar-helm-chart-repo}[{pulsar-helm-chart-repo}] is deprecated and no longer maintained. Use the {kaap-short} instead.
* **Tarball**: Use the tarball provided at {pulsar-repo}/releases[{pulsar-repo}/releases] to install {product} on a server or VM.
* **Ansible**: Use the {company} Ansible scripts provided at {pulsar-ansible-repo}[{pulsar-ansible-repo}] to install {product} on a server or VM with our provided playbooks.

== How do I install {product} in my Kubernetes cluster?

Follow the full instructions in xref:install-upgrade:quickstart-helm-installs.adoc[Quick Start for Helm Chart installs].

== How do I install {product} on my server or VM?

Follow the full instructions in xref:install-upgrade:quickstart-server-installs.adoc[Quick Start for Server/VM installs].

== What task can I perform in the {product} Admin Console?

From the Admin Console, you can:

* Add and run {pulsar-short} clients
* Establish credentials for secure connections
* Define topics that can be published for streaming apps
* Set up {pulsar-short} sinks that publish topics and make them available to subscribers, such as for a {cass-short} database table
* Control namespaces used by {pulsar-short}
* Use the Admin API

== What is {pulsar-short} Heartbeat?

{pulsar-heartbeat-repo}[{pulsar-short} Heartbeat] monitors the availability, tracks the performance, and reports failures of the {pulsar-short} cluster. It produces synthetic workloads to measure end-to-end message pubsub latency. {pulsar-short} Heartbeat is a cloud-native application that can be installed by Helm within the {pulsar-short} Kubernetes cluster.

== What are the features provided by {company} {pulsar} Connector (`pulsar-sink`) that are not supported in `kafka-sink`?

The https://pulsar.apache.org/docs/en/io-overview/[{pulsar-short} IO framework] provides many features that are not possible in {kafka-short}, and has different compression formats and auth/security features. The features are handled by {pulsar-short}. For more, see xref:connectors:index.adoc[{product} IO Connectors].

The {company} {pulsar} Connector allows single-record acknowledgement and negative acknowledgements.

== What features are missing in {company} {pulsar} Connector (`pulsar-sink`) compared with `kafka-sink`?

* No support for `tinyint` (`int8bit`) and `smallint` (`int16bit`).
* The key is always a String, but you can write JSON inside it; the support is implemented in pulsar-sink, but not in {pulsar-short} IO.
* The "value" of a "message property" is always a String; for example, you cannot map the message property to `__ttl` or to `__timestamp`.
* Field names inside structures must be valid for Avro, even in case of JSON structures. For example, field names like `Int.field` (with dot) or `int field` (with space) are not valid.

== How is {company} {pulsar} Connector distributed?

There are two packages:

* The `pulsar-sink` functionality of {company} {pulsar} Connector is included with {product}. It's built in!
* You can optionally download the {company} {pulsar} Connector `.nar` file from the {pulsar-sink-repo}/releases[`pulsar-sink` repository], and then use it as its own product with your open-source {pulsar} install.

If you're using open-source software (OSS) {pulsar}, you can use {company} {pulsar} Connector with the OSS to take advantage of this `pulsar-sink` for {cass-short}.
See the xref:pulsar-connector:ROOT:index.adoc[{company} {pulsar} Connector documentation].

== What is the {company} Change Data Capture (CDC) for {cass-short} connector?

This source connector streams data changes from {cass-short} tables to {pulsar-short} topics.
For more information, see the xref:cdc-for-cassandra:ROOT:index.adoc[{company} CDC for {cass-short} connector documentation].

== What client APIs does {product} provide?

The same as for {pulsar}. See https://pulsar.apache.org/docs/en/client-libraries/.