= {product} Installation on Amazon Elastic Kubernetes Environment
:navtitle: Install on Amazon Elastic Kubernetes Environment

This document covers installation of {product} on the Amazon Elastic Kubernetes Environment (EKS).

For an example set of production cluster values, see the {company} production-ready {pulsar-helm-chart-repo}[Helm chart].

{company} recommends these hardware resources for running {product} in a Kubernetes environment:

include::ROOT:partial$helm-chart-recommendations.adoc[]

For the local machine running the Helm chart, you will need:

* https://helm.sh/docs/[Helm] version 3
* An AWS account with privileges to install and configure Kubernetes resources.

== Helm chart `values.yaml`

The {pulsar-helm-chart-repo}/blob/master/helm-chart-sources/pulsar/values.yaml[`values.yaml`] will deploy {pulsar-short} with:

* One {zookeeper-reg} cluster with `replicaCount:3`
* One {bookkeeper-reg} cluster with `replicaCount:3`
* One broker cluster with `replicaCount: 3`
** Ledgers: `defaultEnsembleSize: 2`, `defaultAckQuorum: 2`, `defaultWriteQuorum: 2`
* One function cluster with a `replicaCount: 2`

=== `default_storage`
The `default_storage` parameter in `values.yaml` controls the default storage class for all persistent volumes created by the Helm chart.

[source,yaml]
----
default_storage:
  existingStorageClassName: default
----

For a component like {bookkeeper-short}, which requires stateful storage, we need to override the `default_storage` class when the {bookkeeper-short} Persistent Volume Claims (PVCs) are created.

There are two ways to override `default_storage`:

* Leave `existingStorageClassName` blank and specify the storage class parameters below.
+
[source,yaml]
----
  volumes:
    journal:
      name: journal
      size: 20Gi
      existingStorageClassName:
        storageClass:
         provisioner: kubernetes.io/aws-ebs
         type: gp2
         fsType: ext4
         extraParams:
            iopsPerGB: "10"
----

* Create a custom storage configuration as a `yaml` file ({pulsar-helm-chart-repo}/blob/master/helm-chart-sources/pulsar/templates/bookkeeper/bookkeeper-storageclass.yaml[like the {company} example]) and tell the Helm chart to use that storage configuration when it creates the {bookkeeper-short} PVCs.
+
[source,yaml]
----
  volumes:
    journal:
      name: journal
      size: 20Gi
      existingStorageClassName: bookkeeper-storageclass.yaml
----

=== EKS-specific storage class

Here is an example `storage-values.yaml` as used above for the {bookkeeper-short} node. Paste it into a `yaml` file to provision a persistent general purpose (`gp2`) SSD with the `ext4` file system.

[source,yaml]
----
storage_class:
    provisioner: kubernetes.io/aws-ebs
    type: gp2
    fsType: ext4
    extraParams:
      iopsPerGB: "10"
----

== Install {product} to EKS

Once you have added your storage settings to the `storage-values.yaml` file, install the Helm chart using the `storage-values.yaml` provisioning.

. Create the namespace. In this example, we use `pulsar`:
+
----
kubectl create namespace pulsar
----

. Run this Helm command using the `storage-values.yaml` provisioning:
+
----
helm install pulsar datastax-pulsar/pulsar --namespace pulsar --values storage_values.yaml --create-namespace
----

. To avoid having to specify the `pulsar` namespace on each subsequent command, set the namespace context. Example:
+
----
`kubectl config set-context $(kubectl config current-context) --namespace=pulsar`
----

. Execute `kubectl get pods -A` to view your running pods.

== Next steps

Once your pods are up and running, continue to xref:install-upgrade:quickstart-helm-installs.adoc[Accessing {pulsar-short} cluster in cloud] to access and manage your cluster.

* To learn more about using the {pulsar-short} Admin Console, see xref:components:admin-console-tutorial.adoc[Admin Console Tutorial].
* To learn more about installing {pulsar-short} on a server or virtual machine, see xref:install-upgrade:quickstart-server-installs.adoc[Quickstart for Server/VM Install].
