= {pulsar-beam} with {product}
:navtitle: {pulsar-beam}
:description: Install a minimal {product} Helm chart that includes {pulsar-beam}
:helmValuesPath: beam

The {pulsar-beam-repo}[{pulsar-beam}] project is an HTTP-based streaming and queueing system for use with {pulsar}.

With {pulsar-beam}, you can send messages over HTTP, push messages to a webhook or cloud function, chain webhooks and functions together, or stream messages through server-sent events (SSE).

In this guide, you'll install a minimal {company} {pulsar-short} Helm chart that includes {pulsar-beam}.

== Prerequisites

* https://helm.sh/docs/intro/install/[Helm 3 CLI] (this example uses version 3.8.0)
* Enough access to a K8s cluster to create a namespace, deployments, and pods
* https://kubernetes.io/docs/tasks/tools/[Kubectl CLI] (this example uses version 1.23.4)

== Install {product} Helm chart

include::partial$install-helm.adoc[]

== Forward service port

In a separate terminal window, port forward the {pulsar-beam} endpoint service:

[source,shell]
----
kubectl port-forward -n datastax-pulsar service/pulsar-proxy 8085:8085
----

The forwarding service will map the URL:PORT https://127.0.0.1:8085 to {pulsar-short} proxy running in the new cluster.
Because {pulsar-beam} was enabled, the proxy knows to forward on to the {pulsar-beam} service.

[source,shell]
----
Forwarding from 127.0.0.1:8085 -> 8085
Forwarding from [::1]:8085 -> 8085
----

== Start a message consumer

In a new terminal window, run the following curl command to begin streaming server-sent events.
See xref:astra-streaming:developing:configure-pulsar-env.adoc[configuring your local environment for {astra-stream}].

[source,shell]
----
TOPIC="my-beam-topic"
curl http://127.0.0.1:8085/v2/sse/persistent/public/default/$TOPIC?SubscriptionInitialPosition=earliest&SubscriptionType=exclusive&SubscriptionName=my-beam-subscription
----

Note the use of `SubscriptionInitialPosition=earliest` in the message consumer.
This instructs {pulsar-beam} to create a subscription on the topic starting at the earliest message.
Try changing the value to `latest` to only receive new messages that arrive.

== Produce a new message

Return to the original terminal window and run the following script to produce a new message.
Don't worry about creating the new topic - if a topic doesn't exist, it is created automatically.

[source,shell]
----
TOPIC="my-beam-topic"
curl --request POST \
  -d "Hi there" \
  http://127.0.0.1:8085/v2/firehose/persistent/public/default/$TOPIC
----

== Consume the message

The message consumer will output the data of the new message just produced.

[source,shell]
----
id: {9 0 0 0 <nil> 0xc002287ad0}
data: Hi there
----

You have now completed the basics of using {pulsar-beam} in a {pulsar-short} cluster. Refer to the project's {pulsar-beam-repo}/blob/master/README.md[readme] to see all the possibilities!

== A Python producer and consumer

This is another example of producing and consuming messages using {pulsar-beam}.
Instead of using curl, this example will use the "requests" Python library to issue HTTP requests.

=== Create project

. Create a new file to hold the Python code.
+
[source,shell]
----
touch beam.py
----

. Paste the following code into "beam.py".
+
[source,python]
----
import requests
import json

beamUrl = "http://127.0.0.1:8085";

tenantName = "public";
namespace = "default";
topicName = "my-beam-topic";

topic = "persistent://{0}/{1}/{2}".format(tenantName, namespace, topicName)

# Produce a message
response = requests.post(beamUrl + "/v2/firehose/persistent/{0}/{1}/{2}".format(tenantName, namespace, topicName), data="Hi there!")
print("Published 1 message ({0})".format(response.status_code))

# Consume a message
response = requests.get(beamUrl + "/v2/poll/persistent/{0}/{1}/{2}?SubscriptionType=shared&SubscriptionInitialPosition=earliest&SubscriptionName=my-beam-subscription".format(tenantName, namespace, topicName))
print("Consumed messages ({0}):\n".format(response.status_code) + json.dumps(response.json(),indent=2))
----

=== Run example Python code

. Run the Python example (we used Python version 3.8.10).
+
[source,shell]
----
python3 beam.py
----

. The output should show 1 message was published and 1 message was consumed.
+
[source,console]
----
Published 1 message (200)
Consumed messages (200):
{
  "limit": 10,
  "size": 1,
  "messages": [
    {
      "payload": "SGkgdGhlcmUh",
      "topic": "persistent://public/default/my-beam-topic",
      "eventTime": "2023-01-03T15:52:24.054Z",
      "publishTime": "2023-01-03T15:52:24.054Z",
      "messageId": "&{ledgerID:16 entryID:0 batchIdx:0 partitionIdx:0 tracker:<nil> consumer:0xc002287e10}",
      "key": ""
    }
  ]
}
----
+
The payload is base64 encoded. Simply decode the string to see the actual message data.

== Clean up

include::partial$cleanup-terminal-and-helm.adoc[]

== Next steps

Here are links to resources and guides you might be interested in:

* {pulsar-beam-repo}[Learn more] about the {pulsar-beam} project
* https://kafkaesque-io.github.io/pulsar-beam-swagger[{pulsar-beam} API]
* xref:pulsar-sql.adoc[]