= {company} Starlight suite of {pulsar-reg} extensions
:navtitle: Starlight

The Starlight suite of extensions is a collection of {pulsar-reg} protocol handlers that extend an existing {pulsar-short} cluster.
The goal of these extensions is to create a native, seamless interaction with a {pulsar-short} cluster using existing tooling and clients.

Each extension integrates two popular event streaming ecosystems, unlocking new use cases and reducing barriers for users adopting {pulsar-short}.
Leverage advantages from each ecosystem to build a truly unified event streaming platform, accelerating the development of real-time applications and services.

The Starlight extensions are open source and included in https://www.ibm.com/docs/en/supportforpulsar[IBM Elite Support for Apache Pulsar].

== {starlight-kafka}

The https://github.com/datastax/starlight-for-kafka[{starlight-kafka} extension] brings native Apache Kafka(R) protocol support to {pulsar} by introducing a Kafka protocol handler on {pulsar-short} brokers.

For more information, see the xref:starlight-for-kafka:ROOT:index.adoc[{starlight-kafka} documentation].

== {starlight-rabbitmq}

The https://github.com/datastax/starlight-for-rabbitmq[{starlight-rabbitmq} extension] brings native RabbitMQ(R) protocol support to {pulsar-reg}.

For more information, see the xref:starlight-for-rabbitmq:ROOT:index.adoc[{starlight-rabbitmq} documentation].

== Starlight for JMS

The https://github.com/datastax/pulsar-jms[Starlight for JMS extension] allows enterprises to take advantage of the scalability and resiliency of a modern streaming platform to run their existing JMS applications.

For more information, see the xref:starlight-for-jms:ROOT:index.adoc[Starlight for JMS documentation].