= Starlight for Luna Streaming

Starlight for Luna Streaming allows enterprises to take advantage of the scalability and resiliency of a modern streaming platform with various connectors for Apache Pulsar(R).

Starlight is open source and is included in https://www.ibm.com/docs/en/supportforpulsar[IBM Elite Support for Apache Pulsar].

== Starlight for Kafka

Starlight for Kafka brings native Apache Kafka(R) protocol support to Apache Pulsar by introducing a Kafka protocol handler on Pulsar brokers.

For more information, see the xref:starlight-for-kafka:ROOT:index.adoc[Starlight for Kafka documentation].

== Starlight for RabbitMQ

Starlight for RabbitMQ(TM) combines the industry-standard AMQP 0.9.1 (RabbitMQ) API with the cloud-native and horizontally scalable Pulsar streaming platform, providing a powerful way to modernize your RabbitMQ infrastructure, improve performance, and reduce costs.

For more information, see the xref:starlight-for-rabbitmq:ROOT:index.adoc[Starlight for RabbitMQ documentation].

== Starlight for JMS

Starlight for JMS allows enterprises to take advantage of the scalability and resiliency of a modern streaming platform to run their existing JMS applications. Because Pulsar is open-source and cloud-native, Starlight for JMS enables enterprises to move their JMS applications to run on-premises and in any cloud environment.

For more information, see the xref:starlight-for-jms:ROOT:index.adoc[Starlight for JMS documentation].