= {product} {pulsar-short} transform functions configuration reference
:navtitle: Transform functions configuration reference

include::common:streaming:partial$transform-functions/intro.adoc[]

To deploy transform functions, see xref:operations:functions.adoc[Deploy and manage functions].

== Configure transform functions

include::common:streaming:partial$transform-functions/config.adoc[]

[#expression-language]
=== Expression language

include::common:streaming:partial$transform-functions/expression-language.adoc[]

[#conditional-steps]
=== Conditional steps

include::common:streaming:partial$transform-functions/when.adoc[]

[#cast]
== Cast

include::common:streaming:partial$transform-functions/cast.adoc[]

[#compute]
== Compute

include::common:streaming:partial$transform-functions/compute.adoc[]

[#drop]
== Drop

include::common:streaming:partial$transform-functions/drop.adoc[]

[#drop-fields]
== Drop fields

include::common:streaming:partial$transform-functions/drop-fields.adoc[]

[#flatten]
== Flatten

include::common:streaming:partial$transform-functions/flatten.adoc[]

[#merge-keyvalue]
== Merge KeyValue

include::common:streaming:partial$transform-functions/merge-keyvalue.adoc[]

[#unwrap-keyvalue]
== Unwrap KeyValue

include::common:streaming:partial$transform-functions/unwrap-keyvalue.adoc[]

////


[#deploy-cli]
== Deploy with {pulsar-short} CLI

https://github.com/datastax/pulsar[Luna Streaming 2.10+] is required to deploy custom functions in {pulsar-short}.

The transform function `.nar` lives in the `/functions` directory of your {pulsar-short} deployment.

[tabs]
======
{pulsar-short} standalone::
+
--
To deploy the built-in transform function locally in {pulsar-short} standalone, do the following:

. Start {pulsar-short} standalone:
+
[source,shell]
----
./bin/pulsar standalone
----

. Create a transform function in `localrun` mode:
+
[source,shell,subs="attributes+"]
----
./bin/pulsar-admin functions localrun \
--jar functions/pulsar-transformations-2.0.1.nar \
--classname com.datastax.oss.pulsar.functions.transforms.TransformFunction \
--inputs my-input-topic \
--output my-output-topic \
--user-config '{"steps": [{"type": "drop-fields", "fields": "password"}, {"type": "merge-key-value"}, {"type": "unwrap-key-value"}, {"type": "cast", "schema-type": "STRING"}]}'
----
--

{pulsar-short} cluster::
+
--
To deploy a built-in transform function to a {pulsar-short} cluster, do the following:

. Create a built-in transform function with the {pulsar-short} CLI:
+
----
./bin/pulsar-admin functions create \
--tenant $TENANT \
--namespace $NAMESPACE \
--name transform-function \
--inputs persistent://$TENANT/$NAMESPACE/$INPUT_TOPIC
--output persistent://$TENANT/$NAMESPACE/$OUTPUT_TOPIC  \
--classname com.datastax.oss.pulsar.functions.transforms.TransformFunction \
--jar functions/pulsar-transformations-2.0.1.nar
----
+
.Result
[%collapsible]
====
[source,console]
----
Created successfully
----
====

. Confirm your function has been created:
+
[source,shell]
----
./bin/pulsar-admin functions list --tenant $TENANT
----
+
.Result
[%collapsible]
====
[source,console]
----
cast-function
flatten-function
transform-function
transform-function-2
----
====

--
======

== Deploy a transform function in a sink

With modern Pulsar versions, transform functions can be deployed inside of a sink process. +
Before this update, functions transformed data either after it was written to a topic by a source connector, or before it was read from a topic by a sink connector. +
This required either an intermediate topic, with additional storage, IO, and latency, or a custom connector. +
Now, functions can be deployed at sink creation and apply preprocessing to sink topic writes. +

Create sink function in pulsar-admin:

https://github.com/datastax/pulsar[Luna Streaming 2.10+] is required to deploy custom functions in {pulsar-short}.

Create a sink connector, and include the path to the transform function and configuration at creation:

[source,shell]
----
pulsar-admin sinks create \
--sink-type elastic-sink \
--inputs my-input-topic \
--tenant public \
--namespace default \
--name my-sink \
--transform-function "builtin://transforms" \
--transform-function-config '{"steps": [{"type": "drop-fields", "fields": "password"}, {"type": "merge-key-value"}, {"type": "unwrap-key-value"}'
----
////