= Luna Streaming IO connectors

When you have Luna Streaming xref:install-upgrade:quickstart-server-installs.adoc[installed] and running, add IO connectors to connect your deployment to external systems like https://cassandra.apache.org/_/index.html[Apache Cassandra], https://www.elastic.co/[ElasticSearch], and more.

[NOTE]
====
There are three versions of the {company} Luna Streaming distribution.
The lunastreaming-all version contains all connectors.
====

[#sink-connectors]
== Sink Connectors

[#astradb-sink]
=== AstraDB sink

The AstraDB sink connector reads messages from {pulsar} topics and writes them to AstraDB systems.

xref:streaming-learning:pulsar-io:connectors/sinks/astra-db.adoc[AstraDB sink documentation]

[#elasticsearch-sink]
=== ElasticSearch sink

The Elasticsearch sink connector reads messages from {pulsar} topics and writes them to Elasticsearch systems.

xref:streaming-learning:pulsar-io:connectors/sinks/elastic-search.adoc[Elasticsearch sink documentation]

[#jdbc-clickhouse-sink]
=== JDBC-Clickhouse sink

The JDBC-ClickHouse sink connector reads messages from {pulsar} topics and writes them to JDBC-ClickHouse systems.

xref:streaming-learning:pulsar-io:connectors/sinks/jdbc-clickhouse.adoc[JDBC ClickHouse sink documentation]

[#jdbc-mariadb-sink]
=== JDBC-MariaDB sink

The JDBC-MariaDB sink connector reads messages from {pulsar} topics and writes them to JDBC-MariaDB systems.

xref:streaming-learning:pulsar-io:connectors/sinks/jdbc-mariadb.adoc[JDBC MariaDB sink documentation]

[#jdbc-postgres-sink]
=== JDBC-PostgreSQL sink

The JDBC-PostgreSQL sink connector reads messages from {pulsar} topics and writes them to JDBC-PostgreSQL systems.

xref:streaming-learning:pulsar-io:connectors/sinks/jdbc-postgres.adoc[JDBC PostgreSQL sink documentation]

[#jdbc-sqlite-sink]
=== JDBC-SQLite

The JDBC-SQLite sink connector reads messages from {pulsar} topics and writes them to JDBC-SQLite systems.

xref:streaming-learning:pulsar-io:connectors/sinks/jdbc-sqllite.adoc[JDBC SQLite sink documentation]

[#kafka-sink]
=== Kafka

The Kafka sink connector reads messages from {pulsar} topics and writes them to Kafka systems.

xref:streaming-learning:pulsar-io:connectors/sinks/kafka.adoc[Kafka sink documentation]

[#kinesis-sink]
=== Kinesis

The Kinesis sink connector reads messages from {pulsar} topics and writes them to Kinesis systems.

xref:streaming-learning:pulsar-io:connectors/sinks/kinesis.adoc[Kinesis sink documentation]

[#snowflake-sink]
=== Snowflake

The Snowflake sink connector reads messages from {pulsar} topics and writes them to Snowflake systems.

xref:streaming-learning:pulsar-io:connectors/sinks/snowflake.adoc[Snowflake sink documentation]

[#source-connectors]
== Source Connectors

[#datagenerator-source]
=== Data Generator source

The Data generator source connector produces messages for testing and persists the messages to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/data-generator.adoc[Data Generator source documentation]

[#debezium-mongodb-source]
=== Debezium MongoDB source

The Debezium MongoDB source connector reads data from Debezium MongoDB systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/debezium-mongodb.adoc[Debezium MongoDB source documentation]

[#debezium-mysql-source]
=== Debezium MySQL source

The Debezium MySQL source connector reads data from Debezium MySQL systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/debezium-mysql.adoc[Debezium MySQL source documentation]

[#debezium-oracle-source]
=== Debezium Oracle source

The Debezium Oracle source connector reads data from Debezium Oracle systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/debezium-oracle.adoc[Debezium Oracle source documentation]

[#debezium-postgres-source]
=== Debezium Postgres source

The Debezium PostgreSQL source connector reads data from Debezium PostgreSQL systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/debezium-postgres.adoc[Debezium PostgreSQL source documentation]

[#debezium-sql-server-source]
=== Debezium SQL Server source

The Debezium SQL Server source connector reads data from Debezium SQL Server systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/debezium-sqlserver.adoc[Debezium SQL Server source documentation]

[#kafka-source]
=== Kafka source

The Kafka source connector reads data from Kafka systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/kafka.adoc[Kafka source connector documentation]

[#kinesis-source]
=== AWS Kinesis source

The AWS Kinesis source connector reads data from Kinesis systems and produces data to {pulsar-short} topics.

xref:streaming-learning:pulsar-io:connectors/sources/kinesis.adoc[Kinesis source connector documentation]

== Experimental Connectors

{company} is always experimenting with connectors.
Below are the connectors available in the luna-streaming-all version of *Luna Streaming*.
We call these *experimental connectors* because they have not yet been promoted to official support in our *Astra Streaming* clusters, but they will work in your Luna Streaming cluster.

[#sink-experimental]
=== Sink Connectors (experimental)

* Cloud Storage
* Kinetica
* Aerospike
* Azure DocumentDB
* Azure Data Explorer (Kusto)
* Batch Data Generator
* Big Query
* CoAP
* Couchbase
* DataDog
* Diffusion
* Flume
* Apache Geode
* Hazelcast
* Apache HBase
* HDFS 2
* HDFS 3
* Humio
* InfluxDB
* JMS
* Apache Kudu
* MarkLogic
* MongoDB
* MQTT
* Neo4J
* New Relic
* OrientDB
* Apache Phoenix
* PLC4X
* RabbitMQ
* Redis
* SAP HANA
* SingleStore
* Apache Solr
* Splunk
* XTDB
* Zeebe

[#source-experimental]
=== Source Connectors (experimental)

* Cassandra Source
* Kinetica
* Azure DocumentDB
* Batch Data Generator
* Big Query
* canal
* CoAP
* Couchbase
* datadog
* diffusion
* DynamoDB
* file
* flume
* Apache Geode
* Hazelcast
* Humio
* JMS
* Apache Kudu
* MarkLogic
* MongoDB
* MQTT
* Neo4J
* Netty
* New Relic
* NSQ
* OrientDB
* Apache Phoenix
* PLC4X
* RabbitMQ
* Redis
* SAP HANA
* SingleStore
* Splunk
* Twitter
* XTDB
* Zeebe

== Next steps

For more on connectors and {pulsar-short}, see xref:streaming-learning:pulsar-io:connectors/index.adoc[] and the https://pulsar.apache.org/docs/2.11.x/io-overview/[{pulsar-short} documentation].